// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyCompany("MacRobert.com")]
[assembly: AssemblyCopyright("Copyright © MacRobert.com 2017")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
[assembly: AssemblyVersion("1.0.6.290")]
[assembly: AssemblyFileVersion("1.0.6.290")]